repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf
        language: python
        args: [-i, -vv]
        types: [python]
        stages: [commit]
      - id: pytest
        name: pytest
        entry: python -m pytest -v
        language: system
        pass_filenames: false
        always_run: true