version: '3.8'

services:
  server:
    container_name: authentication-service
    build: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env.sample
    command: bash -c 'make migrate && uvicorn src.adapters.http.fastapi.main:app --host 0.0.0.0 --port 8000'

  postgres:
    container_name: authentication-service-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: authentication
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - '5432:5432'
